name: Publish

on: [pull_request, push]
jobs:
  build_and_test:
    name: Deploy to Aliyun OSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        id: "cache-cargo"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-mdbook-${{ hashFiles('**/book.toml') }}
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        name: "Install mdBook programs"
        run: "cargo install mdbook mdbook-toc"
      - run: "mdbook build"
      - run: "mv book dist"
      - name: Deploy OSS
        uses: JayMeDotDot/aliyun-OSS-deployer@v1.0.0
        with:
          access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          access-key-secret: ${{ secrets.S3_SECRET_KEY }}
          region: ${{ secrets.S3_REGION }}
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: ${{ secrets.S3_ENDPOINT }}